/**
 * POST /api/ai/quiz
 *
 * Generates 5 JEE-style questions for a subtopic.
 * Questions are generated by Claude using verified content as context,
 * then stored in the DB for future use and answer validation.
 *
 * Returns client-safe questions (NO correctAnswer, NO isCorrect on options).
 */

import { auth } from '@clerk/nextjs/server';
import { NextRequest } from 'next/server';
import { z } from 'zod';
import { anthropic, CLAUDE_MODEL } from '@/lib/ai/client';
import { QUIZ_SYSTEM_PROMPT } from '@/lib/ai/prompts/quiz';
import { retrieveContextForSubtopic } from '@/lib/rag/retrieve';
import { buildQuizContext } from '@/lib/rag/context-builder';
import { QuizQuestionsSchema } from '@/lib/ai/schemas';
import { checkRateLimit } from '@/lib/rate-limit';
import { db } from '@/lib/db/client';
import { questions } from '@/lib/db/schema';
import { getQuestionsForSubtopic, stripAnswerFromQuestion } from '@/lib/db/queries/questions';

const RequestSchema = z.object({
  subtopicId: z.string().uuid(),
});

export async function POST(req: NextRequest) {
  const { userId } = await auth();
  if (!userId) return Response.json({ error: 'Unauthorized' }, { status: 401 });

  const { success } = await checkRateLimit('quiz', userId);
  if (!success) return Response.json({ error: 'Rate limit exceeded' }, { status: 429 });

  let subtopicId: string;
  try {
    const body = await req.json();
    ({ subtopicId } = RequestSchema.parse(body));
  } catch (err) {
    return Response.json({ error: 'Invalid request', detail: String(err) }, { status: 400 });
  }

  // Check if we already have enough verified questions in DB for this subtopic
  const existingQuestions = await getQuestionsForSubtopic(subtopicId, 5);
  if (existingQuestions.length >= 5) {
    // Serve from DB — no AI call needed
    return Response.json({
      success: true,
      data: existingQuestions.map(stripAnswerFromQuestion),
      source: 'database',
    });
  }

  // Not enough questions — generate with Claude
  let context;
  try {
    context = await retrieveContextForSubtopic(subtopicId);
  } catch {
    return Response.json({ error: 'Subtopic not found' }, { status: 404 });
  }

  const ragContext = buildQuizContext(context);
  const userMessage = `${ragContext}\n\nGenerate 5 JEE-style questions for: ${context.targetSubtopic.name}`;

  const message = await anthropic.messages.create({
    model: CLAUDE_MODEL,
    max_tokens: 3000,
    system: QUIZ_SYSTEM_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
  });

  const rawText = message.content[0]?.type === 'text' ? message.content[0].text : '';

  let generatedQuestions;
  try {
    const parsed = JSON.parse(rawText);
    generatedQuestions = QuizQuestionsSchema.parse(parsed);
  } catch (err) {
    console.error('[quiz] Failed to parse Claude response:', rawText.slice(0, 300));
    return Response.json({ error: 'AI generated malformed questions. Please try again.' }, { status: 500 });
  }

  // Save generated questions to DB for future validation
  const savedQuestions = await db
    .insert(questions)
    .values(
      generatedQuestions.map((q) => ({
        subtopicId,
        questionText: q.questionText,
        questionType: q.questionType,
        options: q.options,
        correctAnswer: q.correctAnswer,
        solutionSteps: q.solutionSteps ?? null,
        difficultyLevel: q.difficultyLevel,
        expectedTimeSeconds: q.expectedTimeSeconds,
        conceptsTested: q.conceptsTested,
        source: 'AI_GENERATED' as const,
        status: 'PENDING_REVIEW' as const,
      })),
    )
    .returning();

  // Return client-safe questions (strip correctAnswer)
  return Response.json({
    success: true,
    data: savedQuestions.map(stripAnswerFromQuestion),
    source: 'ai_generated',
  });
}
